/* eslint-disable global-require */
const images = {
  avatar: require('../../assets/images/avatar.png'),
  applogo: require('../../assets/images/appLogo.png'),
  appLogoMin: require('../../assets/images/appLogoMin.png'),
  applogo4x: require('../../assets/images/appLogo4x.png'),
  bg: require('../../assets/images/bg.png'),
  materi: require('../../assets/images/materi.png'),
  kuiz: require('../../assets/images/kuiz.png'),
  lat: require('../../assets/images/lat.png'),
  kami: require('../../assets/images/kami.png'),
  bgh: require('../../assets/images/bgh.png'),
  back: require('../../assets/images/back.png'),
  lock: require('../../assets/images/lock.png'),
  profile: require('../../assets/images/profile.png'),
  bgp: require('../../assets/images/bgp.png'),
  backw: require('../../assets/images/backw.png'),
  member: require('../../assets/images/member.png'),
  email: require('../../assets/images/email.png'),
  ply: require('../../assets/images/ply.png'),
  buttonBlue: require('../../assets/images/buttonBlue.png'),
  gobutton: require('../../assets/images/gobutton.png'),
  eye: require('../../assets/images/hide.png'),
  vie: require('../../assets/images/vie.png'),
  setting: require('../../assets/images/setting.png'),
  bab1: require('../../assets/images/bab1.png'),
  homeActive: require('../../assets/images/homeActive.png'),
  bi: require('../../assets/images/bi.png'),
  biru: require('../../assets/images/Biru.png'),
  kuning: require('../../assets/images/kuning.png'),
  tag: require('../../assets/images/tag.png'),
  bab2: require('../../assets/images/bab2.png'),
  bab3: require('../../assets/images/bab3.png'),
  b: require('../../assets/images/b.png'),
  Rectangle: require('../../assets/images/Rectangle.png'),
  backRegister: require('../../assets/images/backRegister.png'),
  pem: require('../../assets/images/pem.png'),
  pembahasan: require('../../assets/images/pembahasan.png'),
  bgpro: require('../../assets/images/bgpro.png'),
  ehangAbout: require('../../assets/images/ehangAbout.png'),
  ronyAbout: require('../../assets/images/ronyAbout.png'),
  sefuruAbout: require('../../assets/images/sefuruAbout.png'),
  wulanAbout: require('../../assets/images/wulanAbout.png'),
  ciciAbout: require('../../assets/images/ciciAbout.png'),
  ilus: require('../../assets/images/ilus.png'),
  soal: require('../../assets/images/soal.png'),
  no10: require('../../assets/images/no10.png'),
  score: require('../../assets/images/score.png'),
  logout: require('../../assets/images/logout.png'),
  ref: require('../../assets/images/ref.png'),
  m: require('../../assets/images/m.png'),
  n: require('../../assets/images/n.png'),
  o: require('../../assets/images/o.png'),
  p: require('../../assets/images/p.png'),
  q: require('../../assets/images/q.png'),
  r: require('../../assets/images/r.png'),
  quiz: require('../../assets/images/Quiz.png')

  // bgSplash: require('../../assets/images/bgSplash.svg')
  // checkBoxOn: require('../../assets/images/checkbox_on.png'),
  // checkBoxOff: require('../../assets/images/checkbox_off.png'),
  // close: require('../../assets/images/close.png'),
  // dropdown: require('../../assets/images/ic_dropdown.png'),
  // faceSad: require('../../assets/images/face_sad.svg'),
  // login: require('../../assets/images/login.png'),
  // modalCamera: require('../../assets/images/modal_camera.png'),
  // modalGallery: require('../../assets/images/modal_gallery.png'),
  // noConnection: require('../../assets/images/no_connection.png'),
  // onBoarding: [
  //   require('../../assets/images/onBoarding_0.png'),
  //   require('../../assets/images/onBoarding_1.jpg'),
  //   require('../../assets/images/onBoarding_2.png')
  // ],
  // passOff: require('../../assets/images/padlock_off.png'),
  // passOn: require('../../assets/images/padlock_on.png'),
  // search: require('../../assets/images/ic_search.png'),
  // userOff: require('../../assets/images/user_off.png'),
  // userOn: require('../../assets/images/user_on.png')
};

export default images;
